server.port=8081

# 1. In-Memory Connection String (No file-locking issues!)
spring.datasource.url=jdbc:h2:mem:ledgerdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=secure_ledger_pass

# 2. H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# 3. Hibernate/JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true